#!/usr/bin/env bash
# =============================================================================
#  NextGen Accounting — إدارة السيرفر
#  كل عميل = حاوية Docker لوحده + قاعدة بيانات لوحده + رابط HTTPS لوحده
#
#  أول مرة:      deploy/nextgen.sh setup <your-email>   (بعدها الأمر متاح باسم: nextgen)
#  عميل جديد:    nextgen.sh new <client-id> <domain> [--company "Name"] [--tz Africa/Cairo] [--lang ar|en]
#  باقي الأوامر: nextgen.sh help
# =============================================================================
set -euo pipefail

ROOT="${NEXTGEN_ROOT:-/opt/nextgen}"
SELF="$(readlink -f "${BASH_SOURCE[0]}")"
APP_DIR="$(cd "$(dirname "$SELF")/.." && pwd)"
IMAGE="nextgen-accounting:latest"
NET="nextgen"
CADDY="nextgen-caddy"
CONF="$ROOT/nextgen.conf"
DRY_RUN="${DRY_RUN:-0}"            # DRY_RUN=1 يطبع الأوامر بدل تنفيذها (للتجربة)
KEEP_DAYS="${KEEP_DAYS:-30}"       # مدة الاحتفاظ بالنسخ الاحتياطية اليومية
MEM="${CLIENT_MEMORY:-384m}"       # أقصى ذاكرة لكل عميل

say() { printf '%s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
run() {
    if [[ $DRY_RUN == 1 ]]; then
        printf '+'; printf ' %q' "$@"; printf '\n'
    else
        "$@"
    fi
}

require_root() { [[ $DRY_RUN == 1 || $(id -u) -eq 0 ]] || die "run as root (or with sudo)"; }
require_docker() {
    [[ $DRY_RUN == 1 ]] && return 0
    command -v docker >/dev/null 2>&1 || die "Docker is not installed. Install it with:  curl -fsSL https://get.docker.com | sh"
}
load_conf() { if [[ -f $CONF ]]; then source "$CONF"; fi; }
set_conf() {
    local key=$1 val=$2
    mkdir -p "$ROOT"
    touch "$CONF"
    { grep -v "^${key}=" "$CONF" || true; printf '%s=%q\n' "$key" "$val"; } > "$CONF.tmp"
    mv "$CONF.tmp" "$CONF"
    chmod 600 "$CONF"
}

cname() { printf 'nga-%s' "$1"; }
client_dir() { printf '%s/clients/%s' "$ROOT" "$1"; }
client_ids() {
    local d
    for d in "$ROOT"/clients/*/; do
        if [[ -f ${d}client.env ]]; then basename "$d"; fi
    done
    return 0
}
valid_id() {
    local re='^[a-z0-9][a-z0-9-]{1,30}$'
    [[ $1 =~ $re ]] || die "client id must be 2-31 lowercase English letters/digits/dashes (e.g. gulf-trading)"
}
valid_domain() {
    local re='^([a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$'
    [[ $1 =~ $re ]] || die "invalid domain: $1"
}
require_client() {
    valid_id "$1"
    [[ -f $(client_dir "$1")/client.env ]] || die "no such client: $1   (see: nextgen.sh list)"
}
container_exists() {
    [[ $DRY_RUN == 1 ]] && return 1
    docker ps -a --format '{{.Names}}' | grep -qx "$1"
}
container_running() {
    [[ $DRY_RUN == 1 ]] && return 0
    docker ps --format '{{.Names}}' | grep -qx "$1"
}

# ----------------------------------------------------------------- Caddy (HTTPS)
write_caddyfile() {
    load_conf
    local f="$ROOT/Caddyfile" id
    {
        printf '# generated by nextgen.sh - do not edit by hand\n{\n'
        if [[ -n ${ACME_EMAIL:-} ]]; then printf '    email %s\n' "$ACME_EMAIL"; fi
        printf '}\n'
        for id in $(client_ids); do
            (
                source "$(client_dir "$id")/client.env"
                printf '\n%s {\n    encode gzip\n    reverse_proxy %s:8000\n}\n' "$DOMAIN" "$(cname "$id")"
            )
        done
    } > "$f"
}
start_caddy() {
    if container_exists "$CADDY"; then
        run docker start "$CADDY"
        return 0
    fi
    run docker run -d --name "$CADDY" --network "$NET" --restart unless-stopped \
        -p 80:80 -p 443:443 -p 443:443/udp \
        -v "$ROOT/Caddyfile:/etc/caddy/Caddyfile:ro" \
        -v nextgen_caddy_data:/data -v nextgen_caddy_config:/config \
        caddy:2
}
reload_caddy() {
    run docker exec "$CADDY" caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile
}

# ----------------------------------------------------------------- client containers
wait_healthy() {
    [[ $DRY_RUN == 1 ]] && return 0
    local c i
    c=$(cname "$1")
    for i in $(seq 1 40); do
        if docker exec "$c" python -c "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/login', timeout=3)" >/dev/null 2>&1; then
            return 0
        fi
        sleep 1
    done
    docker logs --tail 40 "$c" >&2 || true
    die "client '$1' did not start - see the log above"
}
start_client() {
    local id=$1 dir
    dir=$(client_dir "$id")
    (
        source "$dir/client.env"
        run docker run -d --name "$(cname "$id")" --network "$NET" --restart unless-stopped \
            --memory "$MEM" -e TZ="$CLIENT_TZ" \
            -v "$dir/data:/data" \
            "$IMAGE"
    )
    wait_healthy "$id"
}
backup_one() {
    local id=$1 dir ts dest
    dir=$(client_dir "$id")
    ts=$(date +%F_%H%M%S)
    mkdir -p "$ROOT/backups/$id"
    dest="$ROOT/backups/$id/$id-$ts.db"
    if container_running "$(cname "$id")"; then
        run docker exec "$(cname "$id")" python manage.py backup /data/.host-backup.db
    else
        run docker run --rm -v "$dir/data:/data" "$IMAGE" python manage.py backup /data/.host-backup.db
    fi
    [[ $DRY_RUN == 1 ]] && return 0
    mv "$dir/data/.host-backup.db" "$dest"
    gzip -f "$dest"
    find "$ROOT/backups/$id" -name "$id-*.db.gz" -mtime +"$KEEP_DAYS" -delete
    say "backup: $dest.gz"
}

# ----------------------------------------------------------------- commands
cmd_build() {
    require_docker
    say "building image from $APP_DIR ..."
    run docker build -t "$IMAGE" "$APP_DIR"
}

cmd_setup() {
    local email=${1:-}
    [[ -n $email ]] || die "usage: nextgen.sh setup <your-email>   (used for the free SSL certificates)"
    require_root
    require_docker
    mkdir -p "$ROOT/clients" "$ROOT/backups"
    set_conf ACME_EMAIL "$email"
    if [[ $DRY_RUN == 1 ]] || ! docker network inspect "$NET" >/dev/null 2>&1; then
        run docker network create "$NET"
    fi
    cmd_build
    write_caddyfile
    start_caddy
    install_cron
    run chmod +x "$APP_DIR/deploy/nextgen.sh"
    run ln -sf "$APP_DIR/deploy/nextgen.sh" /usr/local/bin/nextgen
    say ""
    say "Setup complete. From now on you can type: nextgen <command>"
    say "Next: create your first client:"
    say "  nextgen new client1 client1.example.com --company \"Client Co\""
}

install_cron() {
    local line="30 2 * * * root $APP_DIR/deploy/nextgen.sh backup all >> /var/log/nextgen-backup.log 2>&1"
    if [[ $DRY_RUN == 1 ]]; then
        say "+ write /etc/cron.d/nextgen-backup: $line"
        return 0
    fi
    printf 'SHELL=/bin/bash\nPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n%s\n' "$line" > /etc/cron.d/nextgen-backup
    chmod 644 /etc/cron.d/nextgen-backup
}

cmd_new() {
    local id=${1:-} domain=${2:-}
    [[ -n $id && -n $domain ]] || die 'usage: nextgen.sh new <client-id> <domain> [--company "Name"] [--tz Africa/Cairo] [--lang ar|en]'
    shift 2
    local company=$id tz=${DEFAULT_TZ:-Africa/Cairo} lang=ar
    while [[ $# -gt 0 ]]; do
        case $1 in
            --company) company=${2:?--company needs a value}; shift 2 ;;
            --tz) tz=${2:?--tz needs a value}; shift 2 ;;
            --lang) lang=${2:?--lang needs a value}; shift 2 ;;
            *) die "unknown option: $1" ;;
        esac
    done
    valid_id "$id"
    valid_domain "$domain"
    [[ $lang == ar || $lang == en ]] || die "--lang must be ar or en"
    local tzre='^[A-Za-z_]+(/[A-Za-z0-9_+-]+)*$'
    [[ $tz =~ $tzre ]] || die "invalid time zone: $tz (examples: Africa/Cairo, Asia/Dubai, Asia/Riyadh)"
    require_root
    require_docker
    load_conf
    local dir other
    dir=$(client_dir "$id")
    [[ -e $dir ]] && die "client '$id' already exists"
    for other in $(client_ids); do
        if (source "$(client_dir "$other")/client.env"; [[ $DOMAIN == "$domain" ]]); then
            die "domain $domain is already used by client '$other'"
        fi
    done

    mkdir -p "$dir/data"
    run chown 10001:10001 "$dir/data"
    {
        printf 'CLIENT_ID=%q\n' "$id"
        printf 'DOMAIN=%q\n' "$domain"
        printf 'CLIENT_TZ=%q\n' "$tz"
        printf 'CLIENT_LANG=%q\n' "$lang"
        printf 'COMPANY=%q\n' "$company"
        printf 'CREATED=%q\n' "$(date -u +%FT%TZ)"
    } > "$dir/client.env"

    say "initializing database for: $company ..."
    local creds="$dir/ADMIN-CREDENTIALS.txt"
    if [[ $DRY_RUN == 1 ]]; then
        run docker run --rm -e TZ="$tz" -v "$dir/data:/data" "$IMAGE" python manage.py init --company "$company" --lang "$lang"
        printf '  username: admin\n  password: dry-run-password   (temporary)\n' > "$creds"
    elif ! (umask 077; docker run --rm -e TZ="$tz" -v "$dir/data:/data" "$IMAGE" \
                python manage.py init --company "$company" --lang "$lang" > "$creds" 2>&1); then
        cat "$creds" >&2
        rm -rf "$dir"
        die "initialization failed"
    fi
    chmod 600 "$creds"

    start_client "$id"
    write_caddyfile
    reload_caddy

    local user pass
    user=$(sed -n 's/^ *username: *//p' "$creds")
    pass=$(sed -n 's/^ *password: *\([^ ]*\).*/\1/p' "$creds")
    say ""
    say "=================================================================="
    say " Client ready : $company"
    say " URL          : https://$domain"
    say " Username     : $user"
    say " Password     : $pass   (temporary - must be changed at first sign-in)"
    say " Saved in     : $creds"
    say "=================================================================="
    say " The domain must point to this server (DNS A record) for HTTPS to work."
}

cmd_list() {
    printf '%-22s %-42s %-10s %s\n' CLIENT DOMAIN STATUS COMPANY
    local id st
    for id in $(client_ids); do
        (
            source "$(client_dir "$id")/client.env"
            if [[ $DRY_RUN == 1 ]]; then
                st=dry-run
            else
                st=$(docker inspect -f '{{.State.Status}}' "$(cname "$id")" 2>/dev/null || echo missing)
            fi
            printf '%-22s %-42s %-10s %s\n' "$id" "$DOMAIN" "$st" "$COMPANY"
        )
    done
}

cmd_backup() {
    local target=${1:-all} id
    require_root
    require_docker
    load_conf
    if [[ $target == all ]]; then
        for id in $(client_ids); do
            backup_one "$id" || say "WARNING: backup failed for $id"
        done
    else
        require_client "$target"
        backup_one "$target"
    fi
    if [[ -n ${RCLONE_REMOTE:-} ]]; then
        if command -v rclone >/dev/null 2>&1 || [[ $DRY_RUN == 1 ]]; then
            run rclone copy "$ROOT/backups" "$RCLONE_REMOTE" --max-age 48h
        else
            say "WARNING: RCLONE_REMOTE is set but rclone is not installed (apt install rclone)"
        fi
    fi
}

cmd_update() {
    require_root
    require_docker
    load_conf
    cmd_build
    local id
    for id in $(client_ids); do
        say "updating $id ..."
        backup_one "$id"
        run docker rm -f "$(cname "$id")"
        start_client "$id"
    done
    write_caddyfile
    if container_exists "$CADDY" || [[ $DRY_RUN == 1 ]]; then reload_caddy; else start_caddy; fi
    run docker image prune -f
    say "all clients updated"
}

cmd_reset() {
    local id=${1:-} user=${2:-admin}
    [[ -n $id ]] || die "usage: nextgen.sh reset-password <client-id> [username]"
    require_client "$id"
    require_docker
    run docker exec "$(cname "$id")" python manage.py reset-password "$user"
}

cmd_simple() {
    local action=$1 id=${2:-}
    [[ -n $id ]] || die "usage: nextgen.sh $action <client-id>"
    require_client "$id"
    require_docker
    case $action in
        logs) run docker logs --tail 200 -f "$(cname "$id")" ;;
        info) run docker exec "$(cname "$id")" python manage.py info ;;
        *) run docker "$action" "$(cname "$id")" ;;
    esac
}

cmd_remove() {
    local id=${1:-} answer
    [[ -n $id ]] || die "usage: nextgen.sh remove <client-id>"
    require_client "$id"
    require_root
    require_docker
    read -r -p "Type the client id ($id) to confirm removal (data is archived, not deleted): " answer
    [[ $answer == "$id" ]] || die "cancelled"
    backup_one "$id" || true
    if container_exists "$(cname "$id")" || [[ $DRY_RUN == 1 ]]; then run docker rm -f "$(cname "$id")"; fi
    mkdir -p "$ROOT/removed"
    mv "$(client_dir "$id")" "$ROOT/removed/$id-$(date +%F_%H%M%S)"
    write_caddyfile
    reload_caddy
    say "removed $id - data archived in $ROOT/removed/"
}

usage() {
    cat <<EOF
NextGen Accounting - server management   (data root: $ROOT)

First time on a new server:
  setup <email>                          install: HTTPS proxy, image, daily backups

Clients:
  new <id> <domain> [--company "Name"] [--tz Africa/Cairo] [--lang ar|en]
                                         create a client (own database + own HTTPS link)
  list                                   list clients and their status
  info <id>                              company, users, entries for one client
  reset-password <id> [username]         temporary password (default user: admin)
  logs <id> | stop <id> | start <id> | restart <id>
  remove <id>                            remove a client (data is archived, not deleted)

Maintenance:
  backup [all|<id>]                      backup now (also runs daily at 02:30)
  update                                 rebuild from the uploaded code and restart every client
  build                                  only rebuild the image

Examples:
  nextgen.sh setup admin@nextgen-coders.dev
  nextgen.sh new gulf-trading gulf-trading.app.nextgen-coders.dev --company "Gulf Trading LLC" --tz Asia/Dubai --lang en
EOF
}

main() {
    local cmd=${1:-help}
    [[ $# -gt 0 ]] && shift
    case $cmd in
        setup) cmd_setup "$@" ;;
        build) cmd_build ;;
        new) cmd_new "$@" ;;
        list) cmd_list ;;
        backup) cmd_backup "$@" ;;
        update) cmd_update ;;
        reset-password) cmd_reset "$@" ;;
        logs | stop | start | restart | info) cmd_simple "$cmd" "$@" ;;
        remove) cmd_remove "$@" ;;
        help | -h | --help) usage ;;
        *) usage; exit 1 ;;
    esac
}

main "$@"
